version: '3.7'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app

  api_services:
    build: ./services
    ports:
      - "5001:5001"
    volumes:
      - ./services:/app
      - ./api:/usr/src/api
    depends_on:
      - api


networks:
  api:
    external: true